### ISSUE TITLE
Обновление AppMetrica Sdk

### ISSUE THREAD

**Issue by SoratoBlack** [yandexmobile/metrica-plugin-xamarin#10]
от AppStore пришло письмо следующего содержания:
"Your app includes a version of an SDK from Yandex that violates the App Store Review Guidelines. The version of the Yandex SDK you are using in your app attempts to hide the use of private APIs. This is a violation of Sections 2.3.1 and 2.5.1 of the App Store Review Guidelines.

Guideline 2.3.1: Don’t include any hidden or undocumented features in your app.

Guideline 2.5.1: Apps may only use public APIs.

Next Steps

To resolve this issue, please either remove the Yandex SDK entirely from your app, or revise your app to utilize version 2.9.8 or 3.1.2 of the Yandex SDK. Once you have made one of those changes, resubmit your binary for review.

Since your App Store Connect status is Rejected, a new binary will be required."

Насколько я понимаю, проблема в том, что в плагине для Xamarin используется библиотека версии 2.6.5. Используя скрипты update-lib.sh и generate-bindings.sh обновил версию до 2.9.8.
Но проект под IOS собрать не получается. Вылезает огромное количество ошибок. Пробовал менять и PCL Profile77 на Profile92 для версии 4.0,  и на 111 для 4.5,  как советовали ранее.
Подскажите, пожалуйста, каким образом я могу обновить версию SDK или, быть может, поделиться уже собранным плагином.

**Comment by NesterovichAlexey** [comment]
https://github.com/yandexmobile/metrica-plugin-xamarin/issues/9
