### ISSUE TITLE
I'm not able to build projects

### ISSUE THREAD

**Issue by AndreiMisiukevich** [yandexmobile/metrica-plugin-xamarin#4]
Hi.
I tried to build sample project but very strange error occurred.

[iOS]
![1](https://user-images.githubusercontent.com/10124814/26976003-c8f92dfa-4d2a-11e7-9fbb-830730b73252.png)

[Android]
![2](https://user-images.githubusercontent.com/10124814/26976037-e8873d38-4d2a-11e7-8b98-2616c1ce697c.png)

Thanks in advance.

**Comment by bamx23** [comment]
What version of Xamarin Studio and components like SDKs are you using?
