### ISSUE TITLE
Падает при инициализации

### ISSUE THREAD

**Issue by ghost** [yandexmobile/metrica-plugin-xamarin#5]
Совет из другой issue(https://github.com/yandexmobile/metrica-plugin-xamarin/issues/3) с выведением AppMetrica в главный процесс помог, но в этом случае не всегда репорты долетают до дэшборда.

Даже на релизных сборках такая проблема:
![image](https://user-images.githubusercontent.com/5736157/31972734-be976e0a-b92a-11e7-87bb-99ff4a49b71e.png)

```
10-25 02:16:23.897 23983-23983/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: lv.beril.berilhome:Metrica, PID: 23983
                                                   java.lang.UnsatisfiedLinkError: No implementation found for void md5de40f6586ab1fa296e72498ce204b4e1.BerilHomeAndroidApplication.n_onCreate() (tried Java_md5de40f6586ab1fa296e72498ce204b4e1_BerilHomeAndroidApplication_n_1onCreate and Java_md5de40f6586ab1fa296e72498ce204b4e1_BerilHomeAndroidApplication_n_1onCreate__)
                                                       at md5de40f6586ab1fa296e72498ce204b4e1.BerilHomeAndroidApplication.n_onCreate(Native Method)
                                                       at md5de40f6586ab1fa296e72498ce204b4e1.BerilHomeAndroidApplication.onCreate(BerilHomeAndroidApplication.java:25)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by ghost** [comment]
Есть вариант написать нативную Java-библиотеку, которая бы чекала имя процесса при создании `Application` и выполняла определенный callback-инициализацию только лишь _основного_ потока приложения. И этот callback я бы подхватывал через C#-биндинг — перенес бы в него код инициализации Application, но это совсем жуткое решение :С

**Comment by alexsorokoletov** [comment]
Поддержка посоветовала в таком случае такой workaround:

> в этом случае нужно перенести сервис SDK в главный процесс. Для этого, в манифесте у сервиса метрики (MetricaService), уберите строчку android:process=":metrica".

**Comment by ghost** [comment]
@alexsorokoletov Я писал об этом в issue. Так мой кастомный Application-класс инициализируется и AppMertica работает в главном процессе, но не все репорты прилетают в дэшборд.

Проблема в том, что на релизных сборках без галочки `Use Shared Runtime` сам Mono Runtime должен запускаться в отдельном процессе без проблем.

Я так понимаю, решение этой проблемы зависит от ребят из Xamarin.

**Comment by alexsorokoletov** [comment]
У нас тоже кастомный. Замарин немного неактивно отреагировал на проблему. Поэтому мы на некоторое время отключили метрику, попытались починить мультидекс (отключить его и настроить прогард). После недель сражений ответила поддержка метрики и решение их нам подошло.

**Comment by alexsorokoletov** [comment]
Так как проблема на границе двух продуктов, мне не захотелось заниматься поиском правды в этой ситуации. Пользователям нужны фичи, мы для этого готовы пожертвовать метрикой в некотором смысле

**Comment by bamx23** [comment]
Да, мы столкнулись с этой проблемой ещё год назад и тогда я даже на митапе по Xamarin в московском офисе Microsoft про неё рассказал, но до разработчиков среды мои слова не дошли. Сейчас подымаем приоритет задачи и будем пытаться её решить.

**Comment by alexsorokoletov** [comment]
@bamx23 откройте баг на https://bugzilla.xamarin.com/newbug
пошарьте линку на баг, я попрошу ребят из Замарина глянуть.

**Comment by AndreiMisiukevich** [comment]
Подскажите, нужно ли вносить данные изменения в манифест? Или это необходимо только для нативного андроида?
Не совсем понял, исходя из гайда

Спасибо

`<manifest>
    <application>        
             
        <service
            android:name="com.yandex.metrica.MetricaService"
            android:enabled="true"
            android:exported="true"
            android:process=":Metrica">

            <meta-data android:name="metrica:api:level" android:value="64"/>

            <intent-filter>
              <category android:name="android.intent.category.DEFAULT"/>
              <action android:name="com.yandex.metrica.IMetricaService"/>
              <data android:scheme="metrica"/>
            </intent-filter>
        </service>

        <service
            android:name="com.yandex.metrica.ConfigurationService"
            android:enabled="true"
            android:exported="true"
            android:process=":Metrica"
            tools:ignore="ExportedService">
            
            <meta-data
              android:name="metrica:configuration:api:level"
              android:value="2"/>

            <intent-filter>
              <action android:name="com.yandex.metrica.configuration.ACTION_START"/>
            </intent-filter>
        </service>
        
        <service
            android:name="com.yandex.metrica.ConfigurationJobService"
            android:exported="false"
            android:enabled="true"
            android:process=":Metrica"
            android:permission="android.permission.BIND_JOB_SERVICE">
        </service>
         

        <receiver
            android:name="com.yandex.metrica.MetricaEventHandler"
            android:enabled="true"
            android:exported="true">

            
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER"/>
            </intent-filter>
        </receiver>
                
    </application>
</manifest>`

**Comment by ghost** [comment]
@AndreiMisiukevich в каком смысле нативного? Xamarin это тот же native в обертке. Убери все строчки `android:process=":Metrica"` из своего `Manifest.xml`.

**Comment by AndreiMisiukevich** [comment]
@Try4W 
Да проблему я решил, убрав кастомный класс Application'a.

Вопрос был в том, нужно ли всё это добавлять в манифест.
Ответ я получил, что нужно.

Потому как в гайде не совсем прозрачно это написано)

**Comment by alexsorokoletov** [comment]
Мы оставили у себя кастомный класс, проблему решили просто добавлением в манифест следующих строк.

```
<!-- Yandex Metrica required manifest entries START -->
<service android:name="com.yandex.metrica.MetricaService" android:enabled="true" android:exported="true" android:process=":Metrica">
	<intent-filter>
		<category android:name="android.intent.category.DEFAULT" />
		<action android:name="com.yandex.metrica.IMetricaService" />
		<data android:scheme="metrica" />
	</intent-filter>
	<meta-data android:name="metrica:api:level" android:value="50" />
</service>
<receiver android:name="com.yandex.metrica.MetricaEventHandler" android:enabled="true" android:exported="true">
	<!-- Required for tracking campaigns -->
	<intent-filter>
		<action android:name="com.android.vending.INSTALL_REFERRER" />
	</intent-filter>
</receiver>
<!-- end of Yandex Metrica -->
```

Честно говоря, найти в документации эти строки (в итоге нашли их в истории гитхаба) было сложно. Совсем непрозрачно.

Было бы прекрасно, если бы Яндекс еще и версии библиотек обновил. Xamarin SDK использует старые версии Метрики, по сравнению с нативными SDK.

**Comment by bamx23** [comment]
Да, обновление нативных SDK сейчас в процессе для всех плагинов. Xamarin на очереди.

**Comment by NesterovichAlexey** [comment]
В версии 2.0.0 это проблема была решена. Теперь можно использовать кастомный Application класс без проблем.
