### ISSUE TITLE
[Request] DLL on github

### ISSUE THREAD

**Issue by AndreiMisiukevich** [yandexmobile/metrica-plugin-xamarin#7]
Hi
Could you please build projects and upload DLL on github(as it shown here https://tech.yandex.com/appmetrica/doc/mobile-sdk-dg/concepts/xamarin-plugin-docpage/).
Developer will be able to download dll's manually)

Because I can't build ios bindings, some compile errors occur..

thx

**Comment by AndreiMisiukevich** [comment]
Or just give me advice, which packages I should add in my plc/android/ios packages) Because there are several ones on Nuget

Thanks a lot

**Comment by AndreiMisiukevich** [comment]
hmm.. i think, this one https://www.nuget.org/packages/Yandex.Metrica.Xamarin/

It need to updated manual here https://tech.yandex.com/appmetrica/doc/mobile-sdk-dg/concepts/xamarin-plugin-docpage/ ...)

**Comment by NesterovichAlexey** [comment]
Hi. You can fix the compile error by changing the PSL Profile in YandexMetrica.Xamarin.PCL (YandexMetrika.Xamarin.PCL->Project Options->Build->General->.Net Portable->Change) for “PCL 4.0 - Profile92”. In next release we will correct this error.
 
You’re right, it’s https://www.nuget.org/packages/Yandex.Metrica.Xamarin/ needed package(you can find the link in the changelog). We will add in the documentation a way to connect via NuGet.

**Comment by AndreiMisiukevich** [comment]
@NesterovichAlexey thanks a lot, colleague !)
