### ISSUE TITLE
[Android] Crash log appearing

### ISSUE THREAD

**Issue by AndreiMisiukevich** [yandexmobile/metrica-plugin-xamarin#8]
Hi, sometimes app shows crash log, but continue to work (no crash, just error message)

here is my initialization code.

MainApplication.Current -- returns current application (I saving instance in OnCreate method)

var yandexConfigBuilder = YandexConfig.NewConfigBuilder(Config.YandexApiKey);
            yandexConfigBuilder.SetAppVersion(CrossVersion.Current.Version);
            yandexConfigBuilder.SetLogEnabled();
            yandexConfigBuilder.SetReportCrashesEnabled(true);
            yandexConfigBuilder.SetReportNativeCrashesEnabled(true);
            var yandexConfig = yandexConfigBuilder.Build();
            YandexMetrica.Activate(MainApplication.Current.ApplicationContext, yandexConfig);
            YandexMetrica.EnableActivityAutoTracking(MainApplication.Current);

so, after this line
-> YandexMetrica.Activate(MainApplication.Current.ApplicationContext, yandexConfig);

it shows me next message

![photo5404568167482763456](https://user-images.githubusercontent.com/10124814/35056602-66f36f88-fbc3-11e7-880d-b61a11baf256.jpg)

What am I doing wrong? Could you help me?

But i want to notice, that the error doesn't occur after ferst startup, only after second..

**Comment by NesterovichAlexey** [comment]
Hi. This is a similar issue https://github.com/yandexmobile/metrica-plugin-xamarin/issues/5

**Comment by AndreiMisiukevich** [comment]
@NesterovichAlexey thanks a lot!
