### ISSUE TITLE
Есть ли планы обновить библиотеку для поддержания новой версии метрики?

### ISSUE THREAD

**Issue by vfumin** [yandexmobile/metrica-plugin-xamarin#9]
Текущая версия не проходит аппрув в appstore. Есть ли решения?

**Comment by NesterovichAlexey** [comment]
Готовим релиз. В течении пару дней будет

**Comment by AlexandrNikulin** [comment]
@NesterovichAlexey Та же проблема. Очень жду новую версию

**Comment by NesterovichAlexey** [comment]
Релиз уже в проде
